In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_csv(r"C:\Users\sairam\merged dataset.csv")
data.head()

,Unnamed: 0,TP2,TP3,H1,DV_pressure,Reservoirs,Oil_temperature,Flowmeter,Motor_current,COMP,...,gpsSpeed,gpsQuality,month,day,hour,minute,second,fault,location,output
0,1247481,-0.008,8.598,8.604,-0.026,1.696,59.925,18.853406,0.0000,1.0,...,0.0,1.0,1,18,12,31,4,2,3,3
1,1078410,-0.006,9.572,9.580,-0.024,1.708,73.000,19.030938,3.7825,1.0,...,0.0,0.0,1,16,1,33,16,2,3,3
2,1507241,-0.008,9.874,9.880,-0.026,1.704,72.275,19.030938,3.7775,1.0,...,0.0,1.0,1,22,0,57,55,2,3,3
3,598571,-0.008,9.678,9.680,-0.028,1.612,70.000,19.040281,3.7600,1.0,...,29.0,1.0,1,9,12,16,3,2,3,3
4,726390,-0.006,9.818,9.824,-0.026,1.594,72.850,19.030938,3.9350,1.0,...,0.0,1.0,1,11,7,46,20,2,3,3

In [3]:
data=data.drop(['Unnamed: 0'],axis=1)

In [4]:
y1=data['fault']
y2=data['location']
y3=data['gpsQuality']
x=data.drop(['fault','location','gpsQuality'],axis=1)

In [5]:
x=StandardScaler().fit_transform(x)

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train1,y_test1,y_train2,y_test2,t_train3,y_test3=train_test_split(x,y1,y2,y3,stratify=y1,test_size=.2)

In [7]:
from AutoLogging_ML import AutoLogger

In [ ]:
a,model=AutoLogger.train_and_log_classification(x_train,y_train1,x_test,y_test1)

In [ ]:
b,model1=AutoLogger.train_and_log_classification(x_train,y_train2,x_test,y_test2)

In [ ]:
c,model2=AutoLogger.train_and_log_classification(x_train,y_train3,x_test,y_test3)